name: pucardpg
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.1.2

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0
  get: ^4.6.6

  #dateFormat
  intl: ^0.18.1

  #Database
  #  floor: any

  #make request to api
  retrofit: ^3.0.1

  #Hooks
  #  flutter_hooks: ^0.18.3

  #chached image
  cached_network_image: ^3.2.0

  #digit components

  digit_components: ^0.0.2+1
  reactive_forms: ^14.1.0
  flutter_lints: ^2.0.0
  freezed: ^2.4.3
  build_runner: ^2.4.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  json_serializable: ^6.3.1
  watcher: ^1.1.0

  drift: ^2.0.0
  drift_db_viewer: ^2.0.0
  auto_route: ^7.8.4
#  dio: ^5.1.2
  flutter_secure_storage: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  dart_mappable: ^4.2.0
  recase: ^4.1.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  shared_preferences: ^2.1.0
  uuid: ^3.0.6
  collection: ^1.16.0
  location: ^5.0.3
  date_format: ^2.0.7

  google_places_flutter: ^2.0.6
  google_maps_flutter: ^2.2.0
  geocoding: ^2.0.4
  file_picker: ^8.0.0+1
  mime: ^1.0.4
  http_parser: ^4.0.2
  syncfusion_flutter_pdfviewer: any
  permission_handler: ^6.1.1
  open_file: ^3.3.2
  geolocator: ^9.0.1
  url_launcher: ^6.2.6
  country_state_city: ^0.1.6
  http: ^1.2.0
  flutter_svg: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  floor_generator: any
  #  build_runner: any
  #  freezed: ^2.4.7
  #  json_serializable: any
  #  watcher: any
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  auto_route_generator: ^7.3.2
  drift_dev: ^2.14.1
  build_runner: ^2.4.8
  json_serializable: ^6.4.0
  isar_generator: ^3.1.0+1
  dart_mappable_builder: ^4.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - .env
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
