name: application workflow
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/application/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'backend/application/**'
  workflow_dispatch:
jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build and analyze application
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        run: mvn -B -f backend/application/pom.xml verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=pucar_application -Dsonar.organization=pucar -Dsonar.host.url=https://sonarcloud.io/

      - name: Login to Azure Container Registry
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: docker login -u pucardev -p ${{ secrets.ACR_PASSWORD }} pucardev.azurecr.io

      - name: Build and Push Docker image for application
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          docker build --build-arg WORK_DIR="backend/application" -t pucar_application:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker tag pucar_application:v1.0.0-${{ github.sha }} pucardev.azurecr.io/pucar_application:v1.0.0-${{ github.sha }}
          docker push pucardev.azurecr.io/pucar_application:v1.0.0-${{ github.sha }}

      - name: Build and Push Docker image for application_DB
        if: (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main') && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        run: |
          docker build --build-arg WORK_DIR="backend/application/src/main/resources/db" -t pucar_application_db:v1.0.0-${{ github.sha }}  .
          docker tag pucar_application_db:v1.0.0-${{ github.sha }} pucardev.azurecr.io/pucar_application_db:v1.0.0-${{ github.sha }}
          docker push pucardev.azurecr.io/pucar_application_db:v1.0.0-${{ github.sha }}
        working-directory: backend/application/src/main/resources/db
