name: Billing-Service Image Build workflow
on:
  push:
    branches:
      - develop
      - uat-backend
      - dpg-qa-deployment
    paths:
      - 'common/billing-service/**'
  pull_request:
    branches:
      - develop
      - uat-backend
      - dpg-qa-deployment
    paths:
      - 'common/billing-service/**'
  workflow_dispatch:
  workflow_call:
permissions:
  security-events: write
  contents: read
jobs:
  docker_image-build:
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/uat-backend' || github.ref == 'refs/heads/dpg-qa-deployment')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Dependency check
        uses: dependency-check/Dependency-Check_Action@main
        env:
          JAVA_HOME: /opt/jdk
        id: Depcheck
        with:
          project: 'billing-service'
          path: 'common/billing-service'
          format: 'SARIF'
      - name: Upload SARIF result to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: reports/dependency-check-report.sarif
        if: always()

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io
      - name: Git commit_hash for service
        run: |
          commit_hash=$(git log -1 --pretty=format:%H -- common/billing-service)
          echo "commit_hash=$commit_hash" >> $GITHUB_ENV

      - name: Build and Push Docker image for Billing-Service
        run: |
          docker build --build-arg WORK_DIR="common/billing-service" -t pucarsolutionsdev.azurecr.io/pucar_billing:v1.0.0-${{ env.commit_hash }} -f build/maven/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/pucar_billing:v1.0.0-${{ env.commit_hash }}

      - name: Build and Push Docker image for Billing-Service_DB
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/pucar_billing_db:v1.0.0-${{ env.commit_hash }} -f  Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/pucar_billing_db:v1.0.0-${{ env.commit_hash }}
        working-directory: common/billing-service/src/main/resources/db

  Workflow_Trigger:
    if: (github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/uat-backend' || github.ref == 'refs/heads/dpg-qa-deployment')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: docker_image-build
    steps:
      - name: Set Workflow File Based on Branch
        id: set_workflow
        run: |
          if [ "${{ github.ref }}" == "refs/heads/develop" ]; then
            echo "WORKFLOW_FILE=solutions-dev.yaml" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/uat-backend" ]; then
            echo "WORKFLOW_FILE=solutions-uat.yaml" >> $GITHUB_ENV
          elif [ "${{ github.ref }}" == "refs/heads/dpg-qa-deployment" ]; then
            echo "WORKFLOW_FILE=solutions-dpg-qa.yaml" >> $GITHUB_ENV
          fi

      - name: Trigger Deployment Pipeline
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/${{ env.WORKFLOW_FILE }}/dispatches \
          -d '{"ref":"Solutions-Pipeline"}'