name: summons-svc Image Build workflow
on:
  push:
    branches:
      - dpg-qa-deployment
    paths:
      - 'backend/summons-svc/**'
  pull_request:
    branches:
      - dpg-qa-deployment
    paths:
      - 'backend/summons-svc/**'
  workflow_dispatch:
  workflow_call:

jobs:
  docker_image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build and analyze for summons
        env:
          GITHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B -f backend/summons-svc/pom.xml package org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=solutions_summon_svc -Dsonar.organization=solutions -Dsonar.host.url=https://sonarcloud.io/

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        if: github.ref == 'refs/heads/dpg-qa-deployment' && github.event_name == 'push'
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io

      - name: Build and Push Docker image for summons-svc
        if: github.ref == 'refs/heads/dpg-qa-deployment' && github.event_name == 'push'
        run: |
          docker build --build-arg WORK_DIR="backend/summons-svc" -t pucarsolutionsdev.azurecr.io/summons-svc:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/summons-svc:v1.0.0-${{ github.sha }}

      - name: Build and Push Docker image for summons-svc_DB
        if: github.ref == 'refs/heads/dpg-qa-deployment' && github.event_name == 'push'
        run: |
          docker build  -t pucarsolutionsdev.azurecr.io/summons-svc_db:v1.0.0-${{ github.sha }} -f  Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/summons-svc_db:v1.0.0-${{ github.sha }}
        working-directory: backend/summons-svc/src/main/resources/db

  Workflow_Trigger:
    if: github.ref == 'refs/heads/dpg-qa-deployment' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: docker_image-build
    steps:
      - name: Trigger Deployment Pipeline for Solutions Dev
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/solutions-dpg-qa.yaml/dispatches \
          -d '{"ref":"Solutions-Pipeline"}'
