name: analytics Image Build workflow
on:
  push:
    branches:
      - dpg-qa-deployment
    paths:
      - 'backend/analytics/**'
  pull_request:
    branches:
      - dpg-qa-deployment
    paths:
      - 'backend/analytics/**'
  workflow_dispatch:
  workflow_call:

jobs:
  docker_image-build:
    if: github.ref == 'refs/heads/dpg-qa-deployment' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      # Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: docker login -u pucarsolutionsdev -p ${{ secrets.ACR_PASSWORD }} pucarsolutionsdev.azurecr.io

      - name: Build and Push Docker image for analytics
        run: |
          docker build --build-arg WORK_DIR="backend/analytics" -t pucarsolutionsdev.azurecr.io/pucar_analytics:v1.0.0-${{ github.sha }} -f build/maven/Dockerfile .
          docker push pucarsolutionsdev.azurecr.io/pucar_analytics:v1.0.0-${{ github.sha }}


  Workflow_Trigger:
    if: github.ref == 'refs/heads/dpg-qa-deployment' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: docker_image-build
    steps:
      - name: Trigger Deployment Pipeline for Solutions Dev
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GHUB_TOKEN }}" \
          https://api.github.com/repos/pucardotorg/pucar-Devops/actions/workflows/solutions-dpq-qa.yaml/dispatches \
          -d '{"ref":"Solutions-Pipeline"}'
